version: '3.9'

services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming-service
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - DB_HOST=video-db:27017
      - DB_NAME=video-streaming
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
  
  azure-storage:
    image: azure-video-storage-service
    build:
      context: ./azure-video-storage-service
      dockerfile: Dockerfile
    container_name: video-storage
    hostname: video-storage
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=devstoreaccount1
      - STORAGE_ACCESS_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:7777/devstoreaccount1;
    ports:
      - "4001:80"
    restart: "no"
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    container_name: azurite
    command: "azurite -l /workspace -d /workspace/debug.log --blobPort 7777 --blobHost 0.0.0.0 --queuePort 8888 --queueHost 0.0.0.0 --tablePort 9999 --tableHost 0.0.0.0 --loose --skipApiVersionCheck --disableProductStyleUrl"
    volumes:
      - c:/azurite:/workspace
    ports:
      - "7777:7777"
      - "8888:8888"
      - "9999:9999"
  
  video-db:
    image: mongo
    container_name: video-db
    ports:
      - 4002:27017
    volumes:
      - c:/video-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=video-db
